### ISSUE TITLE
Haven't received an API key

### ISSUE THREAD

**Issue by silverjoda** [jbrowell/HEFTcom24#20]
Hello, I registered on the 25th January, and still haven't received my API key. 
I've tried contacting the authors and re-registering but received no response. 
The email that I registered with is tazayev@amp.energy. I might have made a mistake in the email and wrote instead: t.azayev@amp.energy

I don't know who else to ask,
Thanks in advance.

**Comment by jbrowell** [comment]
Hi @silverjoda, I've forwarded your message to the team at Rebase who should be able to get an API sent out to you. I can see that you did register with "t.azayev@amp.energy". I have corrected this in my records.
